jruby wants sqlite3?
attempt at fixing this:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    /home/travis/.rvm/rubies/jruby-head/bin/jruby -r ./siteconf20150820-7416-f71d07.rb extconf.rb 
jruby: warning: unknown property jruby.cext.enabled
jruby: warning: unknown property jruby.cext.enabled
NotImplementedError: C extensions are not supported
    <top> at /home/travis/.rvm/rubies/jruby-head/lib/ruby/stdlib/mkmf.rb:1
  require at org/jruby/RubyKernel.java:939
   (root) at /home/travis/.rvm/rubies/jruby-head/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
    <top> at extconf.rb:1
extconf failed, exit code 1
Gem files will remain installed in /home/travis/build/toadkicker/railsstrap/vendor/bundle/jruby/2.2.0/gems/libv8-3.16.14.11 for inspection.
Results logged to /home/travis/build/toadkicker/railsstrap/vendor/bundle/jruby/2.2.0/extensions/universal-java-1.7/2.2.0/libv8-3.16.14.11/gem_make.out
An error occurred while installing sqlite3 (1.3.10), and Bundler cannot
continue.
Make sure that `gem install sqlite3 -v '1.3.10'` succeeds before bundling.
```